### ISSUE TITLE
Possible issues from importing an AP Full DB Backup

### ISSUE THREAD

**Issue by Mrnofish** [XilinJia/Podcini#24] opened 2024-03-28 02:13 UTC
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/PodVinci/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/PodVinci/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

4.4.0

### Where did you get the app from

Other

### Android version

LOS 20

### Device model

guacamole

### First occurred

Today

### Steps to reproduce

1. Take full DB export from AP
2. Import DB in podcini
3. Navigate to downloads
4. Verify the cache status appears the same as inside AP
5. Check Subs > Statistics > Downloads, the size of the cache is reported to be the same as inside AP

### Expected behaviour

I was expecting the app to behave as its cache was empty.

### Current behaviour

As far as I can remember, the AP cache should be stored inside the app's own directory under Android/data, so Podcini shouldn't be able to access AP's cache.

When I checked Subs > Statistics, the app was claiming the cache was as large as AP's.

I'm not sure what the issue is here, perhaps a snapshot of the cache status is stored inside the DB and the app didn't check it against the filesystem after importing the DB ?

I would expect users switching from AP to try the same, so there may be some thinking about what's appropriate for the app to do in that situation.

Displaying a warning could be a starting point.

**Comment by XilinJia** [comment] 2024-03-28 07:39
Thanks for reporting.  I've noticed this earlier on.  Though I haven't looked into it, I suspected those numbers and info are stored in the DB and so get all imported.  As to the actual downloaded files, they are not imported and don't exist, so some info shown are false.

Yes, I agree this deserves some reasoning.

**Comment by o0nd7ots** [comment] 2024-04-05 21:02
by the way when I imported the antennapod backup all my downloads showed up but upon trying to play them back threw some error and marked as not downloaded.

**Comment by Mrnofish** [comment] 2024-04-05 22:13
@o0nd7ots that's normal, it's due to AP dealing with downloads as a cache: that means the files are all stored stored inside the app's private directory which is inaccessible to other apps.

For a full migration, you'll need a way to copy or move the downloaded files inside Podcini's own cache directory. `adb shell` might be one.

**Comment by o0nd7ots** [comment] 2024-04-06 06:59
I thought that it had something to do with the app isolation.
It is not a problem to me -- I just wanted to let you know in case this was not working as intended.

**Comment by XilinJia** [comment] 2024-05-05 13:44
Since version 4.10.0 and/or AntennaPod 3.3.2, AntennaPod's DB can not be directly imported.  Possibilities need to be investigated.

**Comment by XilinJia** [comment] 2024-06-29 08:41
Podcini.R uses Realm DB, so the SQLite DB of AntennaPod or even Podcini version 5 and below can not be imported reasonable effort.

**Comment by John-Rodriguez-Git** [comment] 2024-12-16 19:06
Maybe if https://github.com/XilinJia/Podcini/issues/49 is fixed, we could use Gpodder to easily migrate from AntennaPod to Podcini?

**Comment by XilinJia** [comment] 2024-12-16 19:23
> Maybe if #49 is fixed, we could use Gpodder to easily migrate from AntennaPod to Podcini?

Sounds interesting.  Note if it ever works, Db import would only be partial as there are uncommon properties in both apps' DB.

**Comment by Mrnofish** [comment] 2024-12-16 22:24
FTR I think Gpodder is still only an option for the tight self-host minority. The public service must have been broken for years on end and there are no alternative instances that I know of?

Additionally, I believe sync through Gpodder would only cover a minimal area, stuff like subscriptions, listened/unlistened status, but I don't think it supports any AP specific features.

I mean, it'd be better than nothing, but the amount of time and effort going into a migration would still be massive, except for sporadic usage cases.

Speaking strictly from a migration stand-point, the option that makes most sense to me would be a companion Wizard app that takes an AP backup file as input, and outputs a Podcini backup to be imported.

That way, the main app would not need to incorporate the SQLite libraries and the conversion logic.

Otherwise, the barrier to switch would be pretty much insurmountable; for instance, I have hundreds of podcasts in AP, each with their settings (tags, speed, and so on) and stats (such as time/episodes played), thousands (probably dozen thousands) of episode statuses (not just played/unplayed but also favorites, inbox status, play progress and probably more).

**Comment by XilinJia** [comment] 2024-12-17 07:02
> a companion Wizard app that takes an AP backup file as input, and outputs a Podcini backup to be imported

Sounds very good.

**Comment by XilinJia** [comment] 2024-12-23 23:04
Podcini 7.0 now supports importing db from antennapod, as well as from Podcast Addict. Let me know your experience.

**Closed** 2024-12-29 14:49 UTC
