### ISSUE TITLE
YouTube playlist support

### ISSUE THREAD

**Issue by Victor239** [XilinJia/Podcini#84] opened 2024-09-01 09:57 UTC
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/podcini/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/Podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

6.5.1

### Where did you get the app from

F-Droid

### Problem you may be having, or feature you want

I'd like to be able to subscribe to a playlist of a channel rather than a whole channel. Many larger channels create so much varied content that I'm not interested in, but they do release some content into narrowly defined playlists that I'd happily subscribe to. 

### Suggested solution

Ability to subscribe to playlists. 

### Screenshots / Drawings / Technical details

Note: playlists already have RSS support, but don't seem to be recognised by Podcini eg https://youtube.com/playlist?list=PLUBKwq0XD0uc8NxCik1bJ-SlZ9cOAkd2R

**Comment by XilinJia** [comment] 2024-09-05 22:33
Thanks for the suggestion. That should be available soon.

**Comment by XilinJia** [comment] 2024-09-14 22:49
in 6.6.3, playlist is handled via share, which should be better than search from within Podcini. Playlist can be subscribed in the same way as a channel.

**Comment by Victor239** [comment] 2024-09-15 22:17
The implementation seems unreliable. Whilst the above playlist works, when I try a random one like https://www.youtube.com/playlist?list=PLvij5I1MVvM1IEs3LJJboEBP7g9R6tCDd it just tries to load infinitely.

**Comment by XilinJia** [comment] 2024-09-16 07:46
I opened the link instantly.

I noticed sometime opening a playlist appear to stuck, I thought it has to do with loading too many episodes, but probably that's not the case.  Sometimes opening it again goes through.  I don't have a good network at the moment, do you?

**Comment by Victor239** [comment] 2024-09-16 13:06
My network is fine. The playlists are each 10 and 12 episodes so I don't know why there's such a difference in behaviour. I've tried several other playlists of similar length and I can only load the original Second Wind one.

**Comment by XilinJia** [comment] 2024-09-16 22:33
I found subscribing to shared playlists pretty smooth on 6.6.4+ (can you detail your operation steps). 
Playing a video episode at times can get stuck. It appears after switching to other episodes and then returning to the stuck episode could make it through.  I'm not sure what are the causes, but suspect perhaps the ads cause it to stuck.

**Comment by Victor239** [comment] 2024-09-17 06:54
I can either select the text for the playlist link in the GitHub app and use the Share pop-up to share it to Podcini (`Add playlist`), or I can follow the playlist link to open it in the YouTube app then try to Share it to Podcini again, both have the same results. I've also tried copying the playlist link into a text editor and sharing it from there with the same results. 

https://youtube.com/playlist?list=PLUBKwq0XD0uc8NxCik1bJ-SlZ9cOAkd2R loads instantly, whilst https://www.youtube.com/playlist?list=PLvij5I1MVvM1IEs3LJJboEBP7g9R6tCDd never finishes loading - there's just the spinner in the middle of the page, with "Online feed" and a back button at the top. Any other arbitrary playlist also never finishes loading e.g. https://www.youtube.com/playlist?list=PLU2851hDb3SGuiXDCZW0GEtXeEsjwobG8.

**Comment by XilinJia** [comment] 2024-09-17 07:34
What version of Podcini are you using?
The 2 never-finish links open instantly in 6.6.6. What I did was copy your link into Youtube, locate the playlist in Youtube, then share it to Podcini.

**Comment by Victor239** [comment] 2024-09-17 08:26
6.6.5. I'll try the next version when it's available on Izzy.

**Comment by XilinJia** [comment] 2024-09-17 12:42
Hum, I'm not sure how much difference 6.6.5 is from 6.6.6 in this respect I was thinking 6.6.3 has some difference).  I'm quite surprised the 2 links didn't work for you. But let me know how 6.6.6 works.

**Comment by Victor239** [comment] 2024-09-17 22:31
Nah no luck with this version either.

**Comment by XilinJia** [comment] 2024-09-17 22:39
Uploading Screen_Recording_20240917_233611_YouTube.mp4…

**Comment by XilinJia** [comment] 2024-09-17 22:40
https://github.com/user-attachments/assets/181ed834-a47a-44c1-8f9a-e88a656183f0

**Comment by Victor239** [comment] 2024-09-18 12:52
Doesn't work with the same procedure https://www.youtube.com/shorts/pYFcT_6bndY)

**Comment by XilinJia** [comment] 2024-09-18 19:31
You are sharing from Brave browser? I can't say what actually is shared from there.  For Podcini to accept the share as a youtube playlist, it checks if the shared address starts with "https://www.youtube.com/playlist?", if not, then the share is passed on to be handled as a normal podcast.  Sorry, it's not that foolproof.

I know share it from Youtube app works.  Can you try it from there as I did?

**Comment by Victor239** [comment] 2024-09-18 23:38
I see the issue - it fails because it expects https://youtube.com, so it doesn't handle https://www.youtube.com nor https://m.youtube.com links.

**Comment by XilinJia** [comment] 2024-09-19 07:53
That should be it.  Will check about other domains later.

**Comment by XilinJia** [comment] 2024-10-06 18:21
https://www.youtube.com/ and https://m.youtube.com/ should work with 6.9.0. See if you find further issues.

**Comment by Victor239** [comment] 2024-10-07 20:24
It seems a bit bugged still - it loads the playlist name and thumbnail but stays showing "0 episodes":

![image](https://github.com/user-attachments/assets/59cb6513-fda6-4c2d-acf3-263f4f8cd40c)

**Comment by XilinJia** [comment] 2024-10-08 03:52
constructing episodes is in the background. If you want to see true number of episodes, you can wait and see the "0 episodes" changes.  Otherwise, you can subscribe at any time and it will be done in the background.

**Comment by XilinJia** [comment] 2024-10-08 07:29
OK, got the culprit. fixed in the coming release.

**Comment by XilinJia** [comment] 2024-10-16 17:33
Youtube Live media can now be accepted as share, with version 6.11.3.

Are there any other issues related to this?

**Comment by Victor239** [comment] 2024-10-17 14:48
Trying to share the playlist using the share button malformed e.g. http://2Fwww.youtube.com%2Fplaylist%3Flist%3DPLWrhB0l2M84m2vwpZXRadL_9YJ1lq4FE6&title=Money+Mondays when it was originally https://www.youtube.com/playlist?list=PLWrhB0l2M84m2vwpZXRadL_9YJ1lq4FE6

Also refreshing doesn't seem to do anything. I can see episodes on YouTube that I can't get into Podcini.

**Comment by XilinJia** [comment] 2024-10-17 18:13
How did you get and where do you see: (http://2fwww.youtube.com%2Fplaylist%3Flist=plwrhb0l2m84m2vwpzxradl_9yj1lq4fe6&title=money+mondays/)

I shared (from Youtube app) the playlist into Podcini and on FeedInfo view the url is neither of the two though similar to the second one. Actually the shared address appears different every time I share (shared to Keep to check), and valid, not the http://2Fwww stuff.

The number of episodes shown in Podcini is 190, while I see on Youtube it says 194.  I don't have much idea on the difference.  How different was yours?

**Comment by Victor239** [comment] 2024-10-17 20:57
Clicking the 3 dot menu then `Share` brings up the malformed URL:
![image](https://github.com/user-attachments/assets/61d4e596-2847-4ca9-be27-d288183f2117)

Mine is 189. I've been unable to refresh to load the latest video from 2 days ago, which is the only new video that been uploaded since I added this playlist to Podcini.

**Comment by XilinJia** [comment] 2024-10-17 21:26
I see, that address is from share-out from Podcini, that should have been handled in the same way as normal podcast. I'm not sure why it's like that, will find out.  Will also try to see why some episodes are missing.

**Comment by XilinJia** [comment] 2024-10-18 06:48
I checked with a few playlists, it appears the number of episodes Podcini gets are the available episodes from the list (some episodes are made unavailable by the uploader for some reason).  For instance, 194 shown on Youtube includes the unavailable episodes (Youtube app shows "unavailable episodes are hidden"), if you count the list (I counted some smaller list to verify), there are only 190 as I get on Podcini.

Will check why the list doesn't update. I know channels update fine.

**Comment by XilinJia** [comment] 2024-10-18 13:33
The share of a feed from Podcini (inherited from AntennaPod) has this:
```
        val text = """
             ${feed.title}
             
            ${URLEncoder.encode(feed.downloadUrl)}&title=${URLEncoder.encode(feed.title)}
             """.trimIndent()
```
I don't what that's for.

**Comment by XilinJia** [comment] 2024-10-26 18:44
in 6.12.6, share in FeedInfo and FeedEpisodes now shares a straight download url of the feed.

**Comment by Victor239** [comment] 2024-10-28 13:21
Thanks, yeah the share URL is fixed. Still have the issue where playlist refresh doesn't update the list.

**Comment by XilinJia** [comment] 2024-10-29 12:43
I wonder if the shared playlist address is static. If you have some updating playlists handy, could you test this:

* share the playlist address from Podcini
* paste it in a browser
* see if it gets updated episodes there

**Comment by Victor239** [comment] 2024-10-30 09:23
The shared playlist address from Podcini is the same as the one that's imported into it. You can use these example addresses for testing https://youtube.com/playlist?list=PLUBKwq0XD0udvQQwx7QOeOmcAAj0yawv1 and https://youtube.com/playlist?list=PLj3yH4lzAY9-PcJMjAgkqcApFl95slr39, they get new additions about once a week so if you leave them in Podcini you'll see they don't get the additions.

**Comment by XilinJia** [comment] 2024-11-05 21:52
playlists update is likely fixed in 6.13.5. Let me know how it works for you.

**Comment by Victor239** [comment] 2024-11-06 20:34
The refresh bug seems fixed :) thanks!

**Comment by XilinJia** [comment] 2024-11-07 05:38
Good. close this now, feel free to reopen with new evidence

**Closed by XilinJia** 2024-11-07 05:38 UTC
